-- Ejecutar en Supabase SQL Editor.
-- Novedades de la página de inicio (gestionadas por Desarrollador/Administrador).
-- Tras crear, ejecuta también backend/sql/alter_inicio_novedades_contrato_lecturas.sql
-- si tu despliegue aún no tiene `inicio_novedades_lecturas` o columna `contrato_id`.

CREATE TABLE IF NOT EXISTS inicio_novedades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id integer REFERENCES contratos (id) ON DELETE SET NULL,
  titulo text NOT NULL,
  resumen text NOT NULL DEFAULT '',
  tipo text NOT NULL DEFAULT 'actualización',
  fecha date NOT NULL DEFAULT (CURRENT_DATE),
  autor text DEFAULT 'Equipo ClaraCore',
  icono text DEFAULT '📢',
  color text DEFAULT '#00B4C6',
  imagen_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_inicio_novedades_created ON inicio_novedades (created_at DESC);

COMMENT ON TABLE inicio_novedades IS 'Novedades mostradas en Módulo Inicio; CRUD vía API admin. Orden por created_at.';

-- Si ya creaste la tabla con la columna "orden", puedes ignorarla o ejecutar:
-- ALTER TABLE inicio_novedades DROP COLUMN IF EXISTS orden;
-- DROP INDEX IF EXISTS idx_inicio_novedades_orden;
