-- Guía pública: Programación de Obra (manual de usuario en módulo Guías).
-- Ejecutar en Supabase después de create_guias.sql.
-- Idempotente: actualiza contenido si el slug ya existe.

INSERT INTO guias (
    contrato_id,
    titulo,
    slug,
    modulo,
    descripcion_corta,
    bloques,
    roles_visibles,
    publicado,
    orden
) VALUES (
    NULL,
    'Programación de Obra',
    'programacion-de-obra',
    'Programación de Obra',
    'Cronograma por PK/tramo: mapa programación/ejecutado SICOE, WBS, CPM, Curva S, sync presupuesto, validación y sellado.',
    $json$[
  {"tipo": "texto", "contenido": "Esta guía explica el módulo Programación de Obra de ClaraCore: cronograma de ejecución sobre el mapa del contrato (PK), versiones baseline y reprogramaciones, ejecución SICOE en mapa y KPI, Curva S, y qué hacer ante alertas habituales."},
  {"tipo": "subtitulo", "contenido": "¿Para qué sirve?"},
  {"tipo": "texto", "contenido": "Programación de Obra permite crear y gestionar el cronograma de ejecución de un contrato de obra vial, integrado con el plano georreferenciado. Usted programa haciendo clic sobre los polígonos del mapa (sectores PK), por agrupadores WBS — no ítem suelto a ítem suelto en una tabla."},
  {"tipo": "subtitulo", "contenido": "Pantalla principal"},
  {"tipo": "texto", "contenido": "Menú lateral → Programación de Obra.\n\n• Mapa central: polígonos PK; toggle **Programación** / **Ejecutado** (esquina superior); basemap Plano / Topo / Satélite; filtro por tramo.\n• Panel KPI ejecución (sobre el mapa): presupuesto del alcance, ejecutado SICOE nivel 1 aprobado, % global; botón ↻ para recalcular.\n• Panel lateral derecho: versión activa, resumen del PK, «+ Nueva versión», historial, envío a validación, Gantt.\n• Cinta superior: Auto-programar, Curva S, Comparar global, exportar MS Project / Excel / PDF, borrar programación del borrador.\n• Modal «Abrir programación»: fechas, dependencias, CPM, comparar vs baseline; vista por PK o tramo consolidado."},
  {"tipo": "subtitulo", "contenido": "Conceptos clave"},
  {"tipo": "texto", "contenido": "PK (polígono): sector del proyecto en el mapa con ítems de presupuesto. Gris oscuro = tiene cantidades pero sin programar.\n\nAgrupador WBS: agrupa ítems bajo una actividad (ej. «Capas Granulares» = 2.1, 2.2, 2.3). La programación es por agrupador. Se crea en Admin → Listado de Precios → «Programación WBS». Sin agrupador, alerta ⚠ y el PK no llega al 100 %.\n\nVersión: baseline (primera oficial), reprogramación, suspensión. Estados: borrador, en validación, sellada (inmutable), archivada.\n\nTramo: varios PK programados juntos en grilla consolidada (cantidades sumadas por agrupador WBS).\n\nDependencias FS/SS/FF/SF entre agrupadores; días hábiles (sin sáb/dom/festivos Colombia).\n\nCPM (ruta crítica): holgura 0 = actividad crítica (⚠); 🏁 = actividad final del tramo. Visible en tabla CPM, Gantt (barras rojas) e informes PDF — no como contorno en el mapa.\n\nBaseline: primera versión sellada; referencia inmutable. Reprogramaciones se comparan contra ella (borde naranja en mapa, pestaña «Comparar vs baseline»).\n\nSync presupuesto: actualiza costos/cantidades de lo **ya programado**; no crea filas nuevas. Ítems nuevos del presupuesto se programan en el modal WBS."},
  {"tipo": "subtitulo", "contenido": "% programado vs % ejecutado"},
  {"tipo": "texto", "contenido": "**% programado** (modo mapa Programación): ítems del presupuesto con fecha asignada ÷ total ítems del PK. NO es obra ejecutada en campo.\n\n**% ejecutado**: costo de registros SICOE con **nivel 1 (inspector) aprobado** ÷ presupuesto del alcance. Solo cuenta cuando nivel1_estado = Aprobado.\n\nDónde ver ejecutado: panel KPI, toggle mapa Ejecutado, Curva S, export PDF/Excel (resumen ejecutivo por capítulo).\n\nModo mapa **Ejecutado** — semáforo por PK:\n• Rojo: 0–25 %\n• Naranja: 25–50 %\n• Amarillo: 50–75 %\n• Cyan: 75–90 %\n• Verde: >90 %\nEn este modo el fondo tenue muestra el estado de programación."},
  {"tipo": "subtitulo", "contenido": "Paso 1 — Configurar agrupadores WBS (obligatorio)"},
  {"tipo": "texto", "contenido": "1. Panel de Administración (⚙) → Listado de Precios.\n2. Vista «Programación WBS».\n3. Por capítulo: «+ Agrupador» → nombre → marcar ítems → «Crear».\n4. Repetir hasta que no queden ítems con ⚠ sin agrupador.\n\nEl sistema tolera formatos distintos al cruzar listado y presupuesto (ej. «3.1» vs «3.1.»)."},
  {"tipo": "subtitulo", "contenido": "Paso 2 — Crear versión baseline"},
  {"tipo": "texto", "contenido": "1. Programación de Obra → «+ Nueva versión».\n2. Primera versión = baseline en borrador.\n3. Selector: «nº1 · baseline · borrador»."},
  {"tipo": "subtitulo", "contenido": "Paso 3 — Programar PK o tramo"},
  {"tipo": "texto", "contenido": "1. Clic en polígono gris oscuro → «Abrir programación».\n2. Por agrupador WBS: fecha inicio, días hábiles (fin automático).\n3. «Guardar cambios».\n4. Colores: amarillo = parcial; azul = completo.\n\nTips:\n• Tramo consolidado: misma grilla para varios PK del tramo.\n• «+ Agregar PK (clic en el mapa)» con modal abierto.\n• «Sincronizar con presupuesto» si cambiaron precios/cantidades del vigente.\n• «Borrar programación» (PK/tramo): solo en borrador; deja el PK gris sin fechas."},
  {"tipo": "subtitulo", "contenido": "Paso 4 — Dependencias y CPM"},
  {"tipo": "texto", "contenido": "1. Modal → pestaña «Dependencias».\n2. Origen → tipo (FS usual) → lag → destino → «+ Agregar».\n3. «Calcular CPM» → tabla con holguras; ⚠ = ruta crítica; 🏁 = fin del tramo.\n4. Gantt: barras rojas = ruta crítica.\n\nSi «CPM desactualizado» → recalcular."},
  {"tipo": "subtitulo", "contenido": "Paso 5 — Validación y sellado"},
  {"tipo": "texto", "contenido": "Prerequisitos: presupuesto 100 % aprobado por interventoría; PKs con fechas donde corresponda.\n\n1. Panel lateral → enviar a validación.\n2. Aprobación secuencial por niveles del contrato.\n3. Último nivel → versión sellada (inmutable)."},
  {"tipo": "subtitulo", "contenido": "Paso 6 — Reprogramar"},
  {"tipo": "texto", "contenido": "1. Historial → «+ Nueva versión» → tipo Reprogramación + motivo.\n2. Clona la anterior; edite solo lo necesario.\n3. Mismo flujo de validación; al sellarse reemplaza la vigente."},
  {"tipo": "subtitulo", "contenido": "Paso 7 — Curva S e informes"},
  {"tipo": "texto", "contenido": "1. Cinta → «Curva S».\n2. **Gráfica**: curvas acumuladas baseline, vigente y ejecutado.\n3. **Tabla del modal**: valores del **mes** (no acumulados).\n4. Brecha presupuesto: costo vigente sin fechas CPM; escenarios opcionales (hasta 5 versiones de presupuesto).\n5. Export PDF o Excel: detalle por PK + resumen ejecutivo con % ejecución por capítulo."},
  {"tipo": "subtitulo", "contenido": "Paso 8 — Ejecución en el mapa (SICOE)"},
  {"tipo": "texto", "contenido": "1. Toggle **Ejecutado** en el mapa.\n2. Colores semáforo según % ejecutado vs presupuesto del PK (ver sección «% programado vs % ejecutado»).\n3. Panel KPI: totales del contrato o tramo filtrado.\n4. Tras aprobar registros en SICOE nivel 1, pulse ↻ en el KPI.\n\nCompare programado (toggle Programación) vs ejecutado (toggle Ejecutado) para detectar rezagos por sector."},
  {"tipo": "subtitulo", "contenido": "Colores del mapa — modo Programación"},
  {"tipo": "texto", "contenido": "• Gris tenue: sin cantidades en presupuesto.\n• Gris oscuro: sin programar.\n• Amarillo: parcialmente programado.\n• Azul: completamente programado.\n• Borde naranja: desviación vs baseline."},
  {"tipo": "subtitulo", "contenido": "Colores del mapa — modo Ejecutado"},
  {"tipo": "texto", "contenido": "Semáforo % ejecutado SICOE N1 vs presupuesto PK:\n• Rojo 0–25 %\n• Naranja 25–50 %\n• Amarillo 50–75 %\n• Cyan 75–90 %\n• Verde >90 %"},
  {"tipo": "subtitulo", "contenido": "Herramientas de la cinta"},
  {"tipo": "texto", "contenido": "• **Auto-programar**: propone fechas secuenciales por agrupador (revise y guarde).\n• **Comparar global**: diferencias entre versiones de programación.\n• **Exportar**: MS Project (.xml), Excel detallado, PDF resumen/Gantt.\n• **Borrar programación del borrador**: elimina fechas de toda la versión en borrador (pide confirmación)."},
  {"tipo": "subtitulo", "contenido": "Alertas comunes"},
  {"tipo": "texto", "contenido": "Ítems sin agrupador WBS → Admin → Programación WBS.\n\nCPM desactualizado → «Calcular CPM».\n\nPresupuesto pendiente de aprobación → interventoría antes de validar cronograma.\n\nPK no pasa a azul → agrupadores WBS + fechas en todos los ítems.\n\nBrecha Curva S → normal si hay costo sin fechas; programe o revise modal Curva S.\n\nEjecutado no sube → solo SICOE nivel 1 aprobado; pulse ↻ KPI.\n\nTras «Borrar programación» → espere el guardado; PK debe quedar gris estable.\n\nÍtem en WBS listado pero no en modal → formato 3.1 vs 3.1.; capítulo e ítem en presupuesto vigente."},
  {"tipo": "subtitulo", "contenido": "Preguntas frecuentes"},
  {"tipo": "texto", "contenido": "¿Programar sin dependencias? Sí; CPM limitado pero fechas funcionan.\n\n¿Varios PK a la vez? Modal abierto → «+ Agregar PK» o tramo consolidado.\n\n¿Borrar fechas? Modal → «Borrar programación» o borrar borrador en cinta.\n\n¿Ver versiones anteriores? Historial (solo lectura).\n\n¿Desviación vs plan original? Borde naranja; «Comparar vs baseline».\n\n¿Sync trae ítems nuevos? No; solo actualiza lo ya programado.\n\n¿Dónde está la ruta crítica? CPM, Gantt, PDF — no en contorno del mapa.\n\n¿Versión programación vs presupuesto? Módulos distintos."},
  {"tipo": "subtitulo", "contenido": "Relación con otros módulos"},
  {"tipo": "texto", "contenido": "• Presupuesto: aprobación interventoría antes de sellar cronograma.\n• SICOE: fuente del % ejecutado (nivel 1 aprobado).\n• Listado de precios (Admin): único lugar para agrupadores WBS.\n• Plano semáforo (Dashboard): mapa distinto; no confundir con Programación.\n\nSi su duda no está cubierta, contacte al administrador del contrato o soporte ClaraCore."}
]$json$::jsonb,
    '{}'::integer[],
    true,
    10
)
ON CONFLICT (slug) DO UPDATE SET
    titulo = EXCLUDED.titulo,
    modulo = EXCLUDED.modulo,
    descripcion_corta = EXCLUDED.descripcion_corta,
    bloques = EXCLUDED.bloques,
    publicado = EXCLUDED.publicado,
    orden = EXCLUDED.orden,
    updated_at = NOW();
